import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "../../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-12 gap-6 px-5 lg:px-48 my-14">
          <div className="col-span-12 p-4 text-center bg-white lg:col-span-3 rounded-2xl"><Sidebar /></div>
          <div className="col-span-12 bg-white lg:col-span-9 rounded-2xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
