import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <div className="grid grid-cols-12 gap-6 my-14 px-6">
          <div className="col-span-3 bg-white rounded-2xl p-4 text-black">
            Sidebar
          </div>
          <div className="col-span-9 bg-gray-800 rounded-2xl p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
